# R Vectors
A vector is simply a list of items that are of the same type.

To combine the list of items to a vector, use the c() function and separate the items by a comma.



In [1]:
fruits <- c("apple", "banana", "cherry")
print(fruits)

[1] "apple"  "banana" "cherry"


In [2]:
# Vector of numerical values
numbers <- c(1, 2, 3)

# Print numbers
numbers

[1] 1 2 3

In [3]:
item_numbers <- c("Apple","Banana", 1,2)

item_numbers

[1] "Apple"  "Banana" "1"      "2"

In [4]:
numbers <- c(1:10)
numbers

[1]  1  2  3  4  5  6  7  8  9 10

In [5]:
numbers <- (1:10)
numbers

[1]  1  2  3  4  5  6  7  8  9 10

In [6]:
# Vector with numerical decimals in a sequence
numbers1 <- 1.5:6.5
numbers1

# Vector with numerical decimals in a sequence where the last element is not used
numbers2 <- 1.5:6.3
numbers2

[1] 1.5 2.5 3.5 4.5 5.5 6.5

[1] 1.5 2.5 3.5 4.5 5.5

In [7]:
# Vector of logical values
log_values <- c(TRUE, FALSE, TRUE, FALSE)

log_values

[1]  TRUE FALSE  TRUE FALSE

# Vector Length
To find out how many items a vector has, use the length() function

In [8]:
fruits <- c("banana", "apple", "orange")

length(fruits)

[1] 3

# Sort a Vector

In [9]:
fruits <- c("banana", "apple", "orange", "mango", "lemon")
numbers <- c(13, 3, 5, 7, 20, 2)

sort(fruits)  # Sort a string
sort(numbers) # Sort numbers

[1] "apple"  "banana" "lemon"  "mango"  "orange"

[1]  2  3  5  7 13 20

# Access Vectors

You can access the vector items by referring to its index number inside brackets []. The first item has index 1, the second item has index 2, and so on

In [10]:
fruits <- c("banana", "apple", "orange")

# Access the first item (banana)
fruits[1]

[1] "banana"

In [11]:
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Access the first and third item (banana and orange)
fruits[c(1, 3)]

[1] "banana" "orange"

In [12]:
fruits <- c("banana", "apple", "orange", "mango", "lemon")

# Access all items except for the first item
fruits[c(-1)]

[1] "apple"  "orange" "mango"  "lemon"

# Change an Item

In [13]:
fruits <- c("banana", "apple", "orange", "mango", "lemon")

#change the first item
fruits[1] <- "pineapple"

# Print fruits
fruits

[1] "pineapple" "apple"     "orange"    "mango"     "lemon"

# Repeat Vectors
 To repeat vectors, use the rep() function

In [14]:
repeat_each <- rep(c(1,2,3), each = 3)

repeat_each

[1] 1 1 1 2 2 2 3 3 3

In [16]:
repeat_each <- rep(c(1,2,3,4,5), each = 5)

repeat_each

[1] 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5

In [17]:
repeat_times <- rep(c(1,2,3), times = 3)

repeat_times

[1] 1 2 3 1 2 3 1 2 3

In [18]:
repeat_indepent <- rep(c(1,2,3), times = c(5,2,1))

repeat_indepent

[1] 1 1 1 1 1 2 2 3

# Generating Sequenced Vectors


In [19]:
numbers <- 1:10

numbers


[1]  1  2  3  4  5  6  7  8  9 10

**To make bigger or smaller steps in a sequence, use the seq() function:**

In [20]:
numbers <- seq(from = 0, to = 100, by = 20)

numbers

[1]   0  20  40  60  80 100

 The seq() function has three parameters: from is where the sequence starts, to is where the sequence stops, and by is the interval of the sequence.

In [21]:
numbers <- seq(from = 10, to = 160, by = 10)

numbers

[1]  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160

# R Lists

A list in R can contain many different data types inside it. A list is a collection of data which is ordered and changeable.

To create a list, use the list() function

In [2]:
#list of strings
fruits <- list("apple", "banana", "orange")
fruits
#list of numerical values
numbers <- list(1, 2, 3)
numbers

# Access list
fruits[[1]]
numbers[[1]]



[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "orange"

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[1] "apple"

[1] 1

# Change Item Value

In [5]:
thislist <- list("apple", "banana", "orange")
thislist[1] <- "mango"

thislist

[[1]]
[1] "mango"

[[2]]
[1] "banana"

[[3]]
[1] "orange"

# List Length

In [6]:
thislist <- list("apple", "banana", "cherry")

length(thislist)


[1] 3

# Check if Item Exists

In [7]:
thsilist <- list("apple", "banana", "cherry")
'apple' %in% thsilist

[1] TRUE

# Add List Items

In [9]:
thislist <- list("apple", "banana", "cherry")
append(thislist, "orange")

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

[[4]]
[1] "orange"

In [14]:
thislist <- list(1,"apple",2, "banana",3, "cherry")
append(thislist, 4)
append(thislist,'orange')

[[1]]
[1] 1

[[2]]
[1] "apple"

[[3]]
[1] 2

[[4]]
[1] "banana"

[[5]]
[1] 3

[[6]]
[1] "cherry"

[[7]]
[1] 4

[[1]]
[1] 1

[[2]]
[1] "apple"

[[3]]
[1] 2

[[4]]
[1] "banana"

[[5]]
[1] 3

[[6]]
[1] "cherry"

[[7]]
[1] "orange"

In [15]:
thislist <- list("apple", "banana", "cherry")

append(thislist, "orange", after = 2)

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "orange"

[[4]]
[1] "cherry"

In [16]:
thislist <- list("apple", "banana", "cherry")

append(thislist, "orange", after = 3)

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

[[4]]
[1] "orange"

# Remove List Items

In [17]:
thislist <- list("apple", "banana", "cherry")

newlist <- thislist[-1]

# Print the new list
newlist

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

# Range of Indexes

In [18]:
thislist <- list("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")

(thislist)[2:5]

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

[[3]]
[1] "orange"

[[4]]
[1] "kiwi"

# Loop Through a List

In [1]:
thislist <- list("Apple","Banana","Orange","Mango","Lemon")

for(x in thislist){
    print(x)
}

[1] "Apple"
[1] "Banana"
[1] "Orange"
[1] "Mango"
[1] "Lemon"


# Join Two Lists
There are several ways to join, or concatenate, two or more lists in R.

The most common way is to use the c() function, which combines two elements together



In [2]:
list1 <- list("a","b","c")
list2 <- list(1,2,3)
list3 <- c(list1,list2)

list3

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[4]]
[1] 1

[[5]]
[1] 2

[[6]]
[1] 3

# R Matrices

# Matrices

A matrix can be created with the matrix() function. Specify the nrow and ncol parameters to get the amount of rows and columns

In [3]:
#create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6,7,8), ncol=2, nrow=4)
thismatrix

[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7   
[4,] 4    8

In [7]:
thismatrix <- matrix(c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20), 
                     ncol=4, nrow=5)
thismatrix

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

In [8]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

# Access Matrix Items

In [14]:
thismatrix <- matrix(c("apple",'banana','cherry','Mango','Lemon','Orange','Peach','Papaya'),
                     nrow=2,ncol=4)
thismatrix
thismatrix[2,4]
thismatrix[1,3]

[,1]   [,2]   [,3]   [,4]  
[1,] apple  cherry Lemon  Peach 
[2,] banana Mango  Orange Papaya

[1] "Papaya"

[1] "Lemon"

In [16]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix
thismatrix[2,]

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

[1] "banana" "orange"

In [18]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

thismatrix
thismatrix[,2]

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

[1] "cherry" "orange"

# Access More Than One Row

In [21]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix
thismatrix[c(1,2),]

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

[,1]   [,2]   [,3] 
[1,] apple  orange pear 
[2,] banana grape  melon

In [22]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix
thismatrix[c(2,3),]

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

[,1]   [,2]      [,3] 
[1,] banana grape     melon
[2,] cherry pineapple fig

# Access More Than One Column

In [24]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix
thismatrix[, c(1,2)]

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

[,1]   [,2]     
[1,] apple  orange   
[2,] banana grape    
[3,] cherry pineapple

In [25]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)

thismatrix
thismatrix[, c(2,3)]

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

[,1]      [,2] 
[1,] orange    pear 
[2,] grape     melon
[3,] pineapple fig

# Add Rows and Columns

Use the cbind() function to add additional columns in a Matrix

In [3]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
thismatrix

newmatrix <- cbind(thismatrix, c("blueberry", "strawberry", "raspberry"))
newmatrix

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

[,1]   [,2]      [,3]  [,4]      
[1,] apple  orange    pear  blueberry 
[2,] banana grape     melon strawberry
[3,] cherry pineapple fig   raspberry

Use the rbind() function to add additional rows in a Matrix

In [5]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
thismatrix

newmatrix <- rbind(thismatrix, c("blueberry", "strawberry", "raspberry"))
newmatrix

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

[,1]      [,2]       [,3]     
[1,] apple     orange     pear     
[2,] banana    grape      melon    
[3,] cherry    pineapple  fig      
[4,] blueberry strawberry raspberry

# Remove Rows and Columns

Use the c() function to remove rows and columns in a Matrix

In [6]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)
thismatrix

[,1]   [,2]     
[1,] apple  orange   
[2,] banana mango    
[3,] cherry pineapple

In [7]:
#Remove the first row and the second column
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)
thismatrix <- thismatrix[-c(1), - c(2)]
thismatrix

[1] "banana" "cherry"

# Check if an Item Exists

In [9]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)

"banana" %in% thismatrix
"kiwi" %in% thismatrix

[1] TRUE

[1] FALSE

# Number of Rows and Columns

Use the dim() function to find the number of rows and columns in a Matrix

In [10]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)
dim(thismatrix)

[1] 3 2

# Matrix Length

Use the length() function to find the dimension of a Matrix

In [11]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)
length(thismatrix)

[1] 6

# Loop Through a Matrix

You can loop through a Matrix using a for loop. The loop will start at the first row, moving right

In [12]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)
nrow(thismatrix)
ncol(thismatrix)

[1] 3

[1] 2

In [14]:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)

thismatrix

for(rows in 1:nrow(thismatrix)){
    for(columns in 1:ncol(thismatrix)){
        print(thismatrix[rows,columns])
    }
}

[,1]   [,2]     
[1,] apple  orange   
[2,] banana mango    
[3,] cherry pineapple

[1] "apple"
[1] "orange"
[1] "banana"
[1] "mango"
[1] "cherry"
[1] "pineapple"


# Combine two Matrices

Again, you can use the rbind() or cbind() function to combine two or more matrices together

In [17]:
matrix1 <- matrix(c(1,2,3,4), nrow = 2, ncol = 2)
matrix2 <- matrix(c(5,6,7,8), nrow = 2, ncol = 2)

c_matrix <- cbind(matrix1, matrix2)
r_matrix <- rbind(matrix1, matrix2)

c_matrix
r_matrix

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

[,1] [,2]
[1,] 1    3   
[2,] 2    4   
[3,] 5    7   
[4,] 6    8

In [18]:
# Combine matrices
Matrix1 <- matrix(c("apple", "banana", "cherry", "grape"), nrow = 2, ncol = 2)
Matrix2 <- matrix(c("orange", "mango", "pineapple", "watermelon"), nrow = 2, ncol = 2)

# Adding it as a rows
Matrix_Combined <- rbind(Matrix1, Matrix2)
Matrix_Combined

# Adding it as a columns
Matrix_Combined <- cbind(Matrix1, Matrix2)
Matrix_Combined

[,1]   [,2]      
[1,] apple  cherry    
[2,] banana grape     
[3,] orange pineapple 
[4,] mango  watermelon

[,1]   [,2]   [,3]   [,4]      
[1,] apple  cherry orange pineapple 
[2,] banana grape  mango  watermelon

# R Arrays

Compared to matrices, arrays can have more than two dimensions.

We can use the array() function to create an array, and the dim parameter to specify the dimensions

In [21]:
# An array with one dimension with values ranging from 1 to 24
thisarray <- c(1:24)
thisarray

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

In [20]:
# An array with more than one dimension
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

In [22]:
thisarray <- c(1:28)
thisarray

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28

In [23]:
thisarray <- array(thisarray, dim = c(4, 7))
thisarray

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 1    5     9   13   17   21   25  
[2,] 2    6    10   14   18   22   26  
[3,] 3    7    11   15   19   23   27  
[4,] 4    8    12   16   20   24   28

In [24]:
thisarray <- array(thisarray, dim = c(4, 7, 2))
thisarray

, , 1

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    1    5    9   13   17   21   25
[2,]    2    6   10   14   18   22   26
[3,]    3    7   11   15   19   23   27
[4,]    4    8   12   16   20   24   28

, , 2

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    1    5    9   13   17   21   25
[2,]    2    6   10   14   18   22   26
[3,]    3    7   11   15   19   23   27
[4,]    4    8   12   16   20   24   28

In [26]:
dim(thisarray)
length(thisarray)
nrow(thisarray)
ncol(thisarray)

[1] 4 7 2

[1] 56

[1] 4

[1] 7

In [32]:
thisarray <- c(1:24)
thisarray
# The syntax is as follow: array[row position, column position, matrix level]
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray

multiarray[2, 3, 2]

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

[1] 22

In [37]:
thisarray <- c(1:24)

# Access all the items from the first row from matrix one
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[c(1),,1]

# Access all the items from the first column from matrix one
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[,c(1),1]

# A comma (,) before c() means that we want to access the column.
# A comma (,) after c() means that we want to access the row.

[1] 1 5 9

[1] 1 2 3 4

In [38]:
multiarray <- array(thisarray, dim = c(4, 3, 2))
result <- multiarray[c(1), , 1]
result


[1] 1 5 9

In [36]:
multiarray <- array(thisarray, dim = c(4, 3, 2))
result <- multiarray[, c(1), 1]
result

[1] 1 2 3 4

# Check if an Item Exists

In [43]:
thisarray <- c(1:26)
multiarray <- array(thisarray, dim = c(3,4,2))
multiarray

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

In [42]:
multiarray[2,3,2]
multiarray[2,3,1]

[1] 20

[1] 8

In [45]:
length(multiarray)
nrow(multiarray)
ncol(multiarray)

[1] 24

[1] 3

[1] 4

In [46]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

2 %in% multiarray

[1] TRUE

# Amount of Rows and Columns

In [47]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

dim(multiarray)

[1] 4 3 2

# Array Length

In [51]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4,3,2))

multiarray
multiarray[2,3,2] <- 100
length(multiarray)

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

[1] 24

# Loop Through an Array

In [53]:
thisarraay <-c(1:30)
multiarray <- array(thisarray, dim = c(5,5,2))

for (x in 1:length(multiarray)){
    print(multiarray[x])
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24
[1] 1
[1] 2


In [54]:
thisarraay <-c(1:50)
multiarray <- array(thisarray, dim = c(5,5,2))

for (x in multiarray){
    print(x)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24
[1] 1
[1] 2


# R Data Frames

Data Frames are data displayed in a format as a table.

Data Frames can have different types of data inside it. While the first column can be character, the second and third can be numeric or logical. However, each column should have the same type of data.

Use the data.frame() function to create a data frame

In [55]:
# Create a data frame
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Print the data frame
Data_Frame

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45

In [65]:
Student_Marks <- data.frame(
  Student_ID = c(1, 2, 3, 4),
  Test_1 = c(40, 50, 60, 70),
  Test_2 = c(45, 55, 65, 75),
  Test_3 = c(48, 58, 68, 78)
)

# Calculate the total marks and add them as a new column
Student_Marks$Total_Marks <- 100

# Calculate the percentage and add it as a new column
Student_Marks$Percentage <- rowSums(Student_Marks[, -1]) / Student_Marks$Total_Marks

# Print the updated data frame
print(Student_Marks)


  Student_ID Test_1 Test_2 Test_3 Total_Marks Percentage
1          1     40     45     48         100       2.33
2          2     50     55     58         100       2.63
3          3     60     65     68         100       2.93
4          4     70     75     78         100       3.23


# Summarize the Data

Use the summary() function to summarize the data from a Data Frame

In [66]:
summary(Student_Marks)

   Student_ID       Test_1         Test_2         Test_3      Total_Marks 
 Min.   :1.00   Min.   :40.0   Min.   :45.0   Min.   :48.0   Min.   :100  
 1st Qu.:1.75   1st Qu.:47.5   1st Qu.:52.5   1st Qu.:55.5   1st Qu.:100  
 Median :2.50   Median :55.0   Median :60.0   Median :63.0   Median :100  
 Mean   :2.50   Mean   :55.0   Mean   :60.0   Mean   :63.0   Mean   :100  
 3rd Qu.:3.25   3rd Qu.:62.5   3rd Qu.:67.5   3rd Qu.:70.5   3rd Qu.:100  
 Max.   :4.00   Max.   :70.0   Max.   :75.0   Max.   :78.0   Max.   :100  
   Percentage   
 Min.   :2.330  
 1st Qu.:2.555  
 Median :2.780  
 Mean   :2.780  
 3rd Qu.:3.005  
 Max.   :3.230  

In [67]:
summary(Data_Frame)

   Training             Pulse          Duration   
 Length:3           Min.   :100.0   Min.   :30.0  
 Class :character   1st Qu.:110.0   1st Qu.:37.5  
 Mode  :character   Median :120.0   Median :45.0  
                    Mean   :123.3   Mean   :45.0  
                    3rd Qu.:135.0   3rd Qu.:52.5  
                    Max.   :150.0   Max.   :60.0  

# Access Items

We can use single brackets [ ], double brackets [[ ]] or $ to access columns from a data frame

In [5]:
Data_Frame <- data.frame(
Training = c("Strength", "Stamina", "Other"),
Pulse = c(100, 150, 120),
Duration = c(60, 30, 45)
)


In [6]:
Data_Frame[1]

Training
1 Strength
2 Stamina 
3 Other

In [2]:
Data_Frame[[1]]

[1] "Strength" "Stamina"  "Other"

In [3]:
Data_Frame$Pulse

[1] 100 150 120

# Add Rows

Use the rbind() function to add new rows in a Data Frame

In [10]:
Data_Frame <- data.frame(
Training = c("Strength",'Stamina','Other'),
Pulse = c(100, 150, 120),
Duration = c(60, 30, 45)
)

new_df_row <- rbind(Data_Frame, c("Strength", 100, 60))
new_df_row

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45      
4 Strength 100   60

# Add Columns

Use the cbind() function to add new columns in a Data Frame

In [13]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Add a new column
New_col_DF <- cbind(Data_Frame, Steps = c(1000, 6000, 2000))

# Print the new column
New_col_DF

Training Pulse Duration Steps
1 Strength 100   60       1000 
2 Stamina  150   30       6000 
3 Other    120   45       2000

In [14]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Add a new column
New_col_DF <- cbind(Data_Frame,  c(1000, 6000, 2000))

# Print the new column
New_col_DF

Training Pulse Duration c(1000, 6000, 2000)
1 Strength 100   60       1000               
2 Stamina  150   30       6000               
3 Other    120   45       2000

# Remove Rows and Columns

Use the subset() function to remove rows and columns from a Data Frame Use the c() function to remove rows and columns in a Data Frame

In [15]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# remove the column
Data_Frame_New <- Data_Frame[-c(1),-c(2)]

# Print the new column
Data_Frame_New

Training Duration
2 Stamina  30      
3 Other    45

# Amount of Rows and Columns

Use the dim() function to find the amount of rows and columns in a Data Frame

In [16]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

dim(Data_Frame)

[1] 3 3

In [17]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

ncol(Data_Frame)
nrow(Data_Frame)

[1] 3

[1] 3

# Data Frame Length

Use the length() function to find the amount of rows and columns in a Data Frame

In [18]:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

length(Data_Frame)

[1] 3

# Combining Data Frames

Use the rbind() and cbind() functions to combine Data FramesUse the rbind() function to combine two or more data frames in R vertically

In [19]:
Data_Frame1 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame2 <- data.frame (
  Training = c("Stamina", "Stamina", "Strength"),
  Pulse = c(140, 150, 160),
  Duration = c(30, 30, 20)
)

New_Data_Frame <- rbind(Data_Frame1, Data_Frame2)
New_Data_Frame

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45      
4 Stamina  140   30      
5 Stamina  150   30      
6 Strength 160   20

In [20]:
Data_Frame3 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame4 <- data.frame (
  Steps = c(3000, 6000, 2000),
  Calories = c(300, 400, 300)
)

New_Data_Frame1 <- cbind(Data_Frame3, Data_Frame4)
New_Data_Frame1

Training Pulse Duration Steps Calories
1 Strength 100   60       3000  300     
2 Stamina  150   30       6000  400     
3 Other    120   45       2000  300

# R Factors

Factors are used to categorize data. Examples of factors are:

Demography: Male/Female
Music: Rock, Pop, Classic, Jazz
Training: Strength, Stamina
To create a factor, use the factor() function and add a vector as argument

In [21]:
# Create a factor
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

# Print the factor
music_genre

[1] Jazz    Rock    Classic Classic Pop     Jazz    Rock    Jazz   
Levels: Classic Jazz Pop Rock

<!-- To only print the levels, use the levels() function -->

In [22]:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

levels(music_genre)


[1] "Classic" "Jazz"    "Pop"     "Rock"

You can also set the levels, by adding the levels argument inside the factor() function

In [23]:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"), levels = c("Classic", "Jazz", "Pop", "Rock", "Other"))

levels(music_genre)

[1] "Classic" "Jazz"    "Pop"     "Rock"    "Other"

# Factor Length

In [24]:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

length(music_genre)

[1] 8

# Access Factors

In [25]:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

music_genre[3]

[1] Classic
Levels: Classic Jazz Pop Rock

# Change Item Value

In [26]:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

music_genre[3] <- "Pop"

music_genre[3]

[1] Pop
Levels: Classic Jazz Pop Rock

In [27]:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"), levels = c("Classic", "Jazz", "Pop", "Rock", "Opera"))

music_genre[3] <- "Opera"

music_genre[3]

[1] Opera
Levels: Classic Jazz Pop Rock Opera